### ISSUE TITLE
Please let me know how I can change the splash screen.

### ISSUE THREAD

**Issue by dreampioneer** [shailesh-ladumor/laravel-pwa#15]
I would like to change splash screen on laravel-pwa.
How can I do this. Should I change manifest.json.
Pleaset let me know ASAP. Please give me the sample how can change splash screen if possible.

**Comment by shailesh-ladumor** [comment]
@dreampioneer this package generates offline HTML, and if you referring to that. than you can find in a public directory

**Comment by dreampioneer** [comment]
> @dreampioneer this package generates offline HTML, and if you referring to that. than you can find in a public directory

I am not sure. I would like to change the splash screen of laravel-pwa on mobile.
I can not find the option to change the splash screen on mobile.
