### ISSUE TITLE
Thank for your reply but I am not sure what you mean.

### ISSUE THREAD

**Issue by dreampioneer** [shailesh-ladumor/laravel-pwa#16]
I am going to change the splash screen of pwa on mobile.
How can I make configuration to do this?
There is icon on center and the app name on bottom on current splash screen of pwa on mobile but I would like to change this splash screen as my custom splash screen.
How can I do this?
Please reply to me ASAP.
Thanks.

**Comment by shailesh-ladumor** [comment]
Can you share screenshot of existing splash screen?

**Comment by dreampioneer** [comment]
Thanks for your reply.
![image](https://github.com/shailesh-ladumor/laravel-pwa/assets/143971762/911aaab3-ec8a-47c2-aeda-ad378f63e471)
This is the screen shot of the splash.

**Comment by shailesh-ladumor** [comment]
@dreampioneer it looks like Android or mobile stuff. not related to this package. you can open the issue again if you have any issues with this package. Thanks for reaching out here.
