### ISSUE TITLE
Add to home screen button/banner invitation?

### ISSUE THREAD

**Issue by pixsolution** [shailesh-ladumor/laravel-pwa#17]
Hello, thanks for your package, I followed your steps and in my console see "Service worker registration succeeded..." but in PC browser don't see the add home button that you show on https://www.youtube.com/watch?v=9H-T81KQPyo and on my mobile don't see add to home screen button/banner invitation, I only see the option if I open menu attached screenshot
<img width="133" alt="1" src="https://github.com/shailesh-ladumor/laravel-pwa/assets/47191848/b99ff2ef-3a0b-4e24-bb86-0c092e2a617f">
do you know how can I add the home screen button/banner invitation on mobile?

I'm using:
 "laravel/framework": "^9.19", come with vite
 "laravel/jetstream": "^2.12",
"livewire/livewire": "^2.5",

**Comment by shailesh-ladumor** [comment]
Is there any other error in the console? it should show.

**Comment by pixsolution** [comment]
yes it with https://staging.saludvitale.com.pa/
attached screenshot of the console
<img width="925" alt="1a" src="https://github.com/shailesh-ladumor/laravel-pwa/assets/47191848/b1ee0129-9eed-450a-a270-a4be5b93a010">
