### ISSUE TITLE
Get an error in console from the generated sw.js

### ISSUE THREAD

**Issue by tanthammar** [shailesh-ladumor/laravel-pwa#2]
Chrome version
Version 99.0.4844.84 (Officiell version) (arm64)

```
Uncaught (in promise) TypeError: Failed to execute 'put' on 'Cache': Request scheme 'chrome-extension' is unsupported
    at sw.js:39:26
```
<img width="454" alt="image" src="https://user-images.githubusercontent.com/21239634/162766854-f13f41a7-243d-46df-b946-b2cb9179869c.png">

**Comment by shailesh-ladumor** [comment]
@tanthammar as per your [PR](https://github.com/shailesh-ladumor/laravel-pwa/pull/3). this issue is no more. Thanks
