### ISSUE TITLE
pwa on mobile

### ISSUE THREAD

**Issue by vaskomichal** [shailesh-ladumor/laravel-pwa#4]
Hi, I tried to install clean laravel 8 project with your project Like a web I used the default welcome view from laravel. On desktop, everything works fine but when I saved PWA on the home screen on mobile and open it again from home screen I got 404. Can't you advise me why?

Thanks!

**Comment by shailesh-ladumor** [comment]
@vaskomichal did you configure and properly installed it? please see this tutorial [once](https://www.youtube.com/watch?v=9H-T81KQPyo) may be helpfull

**Comment by shailesh-ladumor** [comment]
because it's working fine for me
![image](https://user-images.githubusercontent.com/16555999/166400922-13f1c41e-b911-4706-a3e6-d9e632a81e62.png)
