### ISSUE TITLE
on server

### ISSUE THREAD

**Issue by Abdurashid-dev** [shailesh-ladumor/laravel-pwa#5]
It doesn't work on server and also I have some errors in console

**Comment by shailesh-ladumor** [comment]
please send error here

**Comment by shailesh-ladumor** [comment]
Do have https on your server?

**Comment by Abdurashid-dev** [comment]
yep

**Comment by faith-code-exe** [comment]
I also have the same issue. Is there a solution on this problem?

**Comment by Abdurashid-dev** [comment]
solving this problem is westing your time

**Comment by faith-code-exe** [comment]
> yep

is there another plugin that you can recommend to me?

**Comment by faith-code-exe** [comment]
> solving this problem is westing your time
is there another plugin that you can recommend to me?

**Comment by Abdurashid-dev** [comment]
> 

It is better to write in the native language for mobile apps

**Comment by Abdurashid-dev** [comment]
> > solving this problem is westing your time
> 
> is there another plugin that you can recommend to me?



> > solving this problem is westing your time
> 
> is there another plugin that you can recommend to me?

It is better to write in the native language for mobile apps
