### ISSUE TITLE
Is it possible to use with inertia

### ISSUE THREAD

**Issue by chantouchsek** [shailesh-ladumor/laravel-pwa#9]
I want to use this package with inertia to make it work, is it possible and how?

**Comment by EmmanuelMartinez** [comment]
I still use inerta, jetstream with vue 3, it is possible to make this package work with this stack?

**Comment by shailesh-ladumor** [comment]
> I still use inerta, jetstream with vue 3, it is possible to make this package work with this stack?

never tested. you can test it.

**Comment by bhaviljain68** [comment]
> I want to use this package with inertia to make it work, is it possible and how?

Hey buddy... did you ever get around to trying this with inertia??

**Comment by zckyachmd** [comment]
> > I want to use this package with inertia to make it work, is it possible and how?
> 
> Hey buddy... did you ever get around to trying this with inertia??

I'm trying to install on Laravel Jetstream using Inertia.js & Vue.js 3. It's not working properly

**Comment by chantouchsek** [comment]
I have no idea, but I don't think it's working....

**Comment by shailesh-ladumor** [comment]
please check. https://laracasts.com/discuss/channels/general-discussion/no-address-bar?page=1&replyId=771360 may be it's working with Inertia.js. I will confirm soon it's working or not.

**Comment by zckyachmd** [comment]
> please check. https://laracasts.com/discuss/channels/general-discussion/no-address-bar?page=1&replyId=771360 may be it's working with Inertia.js. I will confirm soon it's working or not.

Please try with Laravel 10, because Laravel Mix is replaced with Vite. Maybe that's why I failed to run the PWA, CMIIW

**Comment by bhaviljain68** [comment]
> please check. https://laracasts.com/discuss/channels/general-discussion/no-address-bar?page=1&replyId=771360 may be it's working with Inertia.js. I will confirm soon it's working or not.

Hey.. Did you get around to trying this with Inertia + Vite Setup??

**Comment by shailesh-ladumor** [comment]
> I have no idea, but I don't think it's working....

It would be good If share error here

**Comment by shailesh-ladumor** [comment]
> > please check. https://laracasts.com/discuss/channels/general-discussion/no-address-bar?page=1&replyId=771360 may be it's working with Inertia.js. I will confirm soon it's working or not.
> 
> Hey.. Did you get around to trying this with Inertia + Vite Setup??

yes, It's working with Vite because this package does not depend on Vite or mix, 

I installed in the laravel latest version and see the output here
 
![image](https://github.com/shailesh-ladumor/laravel-pwa/assets/16555999/2813b1d3-1713-49a9-91d3-17609091159e)

**Comment by bhaviljain68** [comment]
> > > please check. https://laracasts.com/discuss/channels/general-discussion/no-address-bar?page=1&replyId=771360 may be it's working with Inertia.js. I will confirm soon it's working or not.
> > 
> > Hey.. Did you get around to trying this with Inertia + Vite Setup??
> 
> 
> yes, It's working with Vite because this package does not depend on Vite or mix, 
> 
> I installed in the laravel latest version and see the output here
>  
> ![image](https://github.com/shailesh-ladumor/laravel-pwa/assets/16555999/2813b1d3-1713-49a9-91d3-17609091159e)
> 
> Make sure you are not checking with virtual host. because PWA only work https. you can setup HTTPS in virtual host. see [video ](https://youtu.be/D5IqDcHyXSQ)here 

Thats awesome!!!😃😃😃😃😃

Ill try to implement this on monday to see how it works...
